---
title: "Not able to create emails on Adobe Campaign Standard Instance"
description: "Learn how to fix the Adobe Campaign Classic issue where users are getting an error when creating an email using the home widget or through a workflow."
solution: Campaign
product: Campaign
applies-to: "Campaign Classic"
keywords: "KCS, Adobe Campaign Standard , email error, Adobe Campaign Standard Instance"
resolution: Resolution
internal-notes: "Ticket = TK206238, R&D JIRA = https://jira.corp.adobe.com/browse/CAMP-39887"
bug: False
article-created-by: Zita Rodricks
article-created-date: "6/18/2024 1:46:11 PM"
article-published-by: Zita Rodricks
article-published-date: "6/18/2024 1:53:50 PM"
version-number: 6
article-number: KA-15225
dynamics-url: "https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=fa9ba41b-792d-ef11-840a-002248084fbb"

---
# Not able to create emails on Adobe Campaign Standard Instance


Learn how to fix the Adobe Campaign Classic issue where users are getting the following error when creating an email using the home widget or through a workflow.

## Description {#description}


### <b>Environment</b>

Campaign Classic



### <b>Issue/Symptoms</b>

Some users are getting the following error when creating an email using the home widget or by clicking create in Marketing Activities or through a workflow.

Error: *Uncaught TypeError: Cannot read property 'metamodel' of null
Pile d'exécution : TypeError: Cannot read property 'metamodel' of null at Object.onSuccess*



<b>Steps to reproduce</b>

- Log in to the instance.
- Go to Home Page. Click on <b>Create an Email </b>`>`  the error will appear.
- Go to the Marketing Activities. Click on <b>Create</b>. Select <b>Email Delivery </b>`>`   the error will appear.
- Create a workflow. Add a Delivery activity. Open the <b>activity `>` </b> the error will appear.



## Resolution {#resolution}


Clear the cache.
<b>Cause</b>
The issue seems to be caused by a cache issue in the browser. When the users logged in to the instance using the incognito mode of another browser, they do not face this issue.
